// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgoylRwpZJsfT2qAvmxW9gtki5LxoPPJk',
    appId: '1:344174596166:web:981ff9de8e5fbd2ed53a47',
    messagingSenderId: '344174596166',
    projectId: 'banking-c1470',
    authDomain: 'banking-c1470.firebaseapp.com',
    storageBucket: 'banking-c1470.firebasestorage.app',
    measurementId: 'G-8XWBY7YD9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_1AwihTTzPGFmT7LOznPI883MX04qzc',
    appId: '1:344174596166:android:a35664a316de2b90d53a47',
    messagingSenderId: '344174596166',
    projectId: 'banking-c1470',
    storageBucket: 'banking-c1470.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-YAdb9OYB5tuExPIzlth3VW0cvVcnow',
    appId: '1:344174596166:ios:c273b38f0c7325c3d53a47',
    messagingSenderId: '344174596166',
    projectId: 'banking-c1470',
    storageBucket: 'banking-c1470.firebasestorage.app',
    iosClientId: '344174596166-3r6fklg4eh6foas77rarc9fvmhncvvdo.apps.googleusercontent.com',
    iosBundleId: 'com.usmanmallana.mobileBanking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-YAdb9OYB5tuExPIzlth3VW0cvVcnow',
    appId: '1:344174596166:ios:c273b38f0c7325c3d53a47',
    messagingSenderId: '344174596166',
    projectId: 'banking-c1470',
    storageBucket: 'banking-c1470.firebasestorage.app',
    iosClientId: '344174596166-3r6fklg4eh6foas77rarc9fvmhncvvdo.apps.googleusercontent.com',
    iosBundleId: 'com.usmanmallana.mobileBanking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgoylRwpZJsfT2qAvmxW9gtki5LxoPPJk',
    appId: '1:344174596166:web:981ff9de8e5fbd2ed53a47',
    messagingSenderId: '344174596166',
    projectId: 'banking-c1470',
    authDomain: 'banking-c1470.firebaseapp.com',
    storageBucket: 'banking-c1470.firebasestorage.app',
    measurementId: 'G-8XWBY7YD9T',
  );
}
